Download INITRAMFS, cleanup build container

diff --git a/coinbootmaker b/coinbootmaker
--- a/coinbootmaker
+++ b/coinbootmaker
@@ -1,7 +1,7 @@
 #!/bin/bash -e
-#set -x
+set -x
 
-# Copyright (C) 2018, 2019 Gunter Miegel coinboot.io
+# Copyright (C) 2018 - 2021 Gunter Miegel coinboot.io
 #
 # This file is part of Coinboot.
 # This software may be modified and distributed under the terms
@@ -16,7 +16,7 @@ display_help() {
   echo
   echo 'Packaged Coinboot pluings are written to the ./builds directory'
   echo
-  echo 'Usage: coinbootmaker [-i] [-h] -p <file name> <path to initramfs> '
+  echo 'Usage: coinbootmaker [-i] [-h] [-p <file name> <path to initramfs>]'
   echo
   echo '-i              Interactive mode - opens a shell in the build environment'
   echo '-p <file name>  Plugin to build'
@@ -44,26 +44,64 @@ done
 
 shift $((OPTIND -1))
 
+
+WGET='wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0'
+CURL='curl --max-time 5 --retry-max-time 20 --retry 999'
+CACHE_DIR=$(readlink -f ./cache)
+GITHUB_REPO=frzb/coinboot
+RELEASE=latest
+## initramfs and kernel vmlinuz ##
+# RELEASE is set via an environment variable under ./conf/environment
+# If the value is 'latest' we determine the latest release, else we use the set value.
+
+if [ $RELEASE = latest ]; then
+  RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
+  sleep 5
+  while ! TAG=$(echo $RESPONSE | jq -r '.[0].name'); do
+    echo "Calling the Github API has failed, repeat ..."
+    RESPONSE=$($CURL --silent "https://api.github.com/repos/${GITHUB_REPO}/tags")
+      sleep 5
+    done
+  echo "Using latest coinboot-debirf release: $TAG"
+fi
+
+DOWNLOAD_URL=https://github.com/${GITHUB_REPO}/releases/download/${TAG}
+
+if [ -z $KERNEL ]; then
+  KERNEL=4.15.0-72-generic
+fi
+INITRAMFS=coinboot-initramfs-$KERNEL
+
+if ! [ -f $CACHE_DIR/$INITRAMFS ]; then
+$WGET $DOWNLOAD_URL/$INITRAMFS -P $CACHE_DIR
+fi
+
 BASEDIR=$PWD
-INITRAMFS=$(readlink -f $1)
+#INITRAMFS=$(readlink -f $1)
 LOWER=/tmp/$(basename $INITRAMFS)_extracted_by_coinbootmaker/lower
 UPPER=/tmp/$(basename $INITRAMFS)_extracted_by_coinbootmaker/upper
 WORKING_DIRECTORY=/tmp/$(basename $INITRAMFS)_extracted_by_coinbootmaker/working_dir
 MERGED=/tmp/$(basename $INITRAMFS)_extracted_by_coinbootmaker/merged
 
-#while ! sudo runc list | grep coinbootmaker | grep stopped; do
-#  echo 'Waiting for Coinbootmaker container to be stopped ...'
-#  sleep 1
-#done
-#sudo runc delete coinbootmaker
-sudo runc kill coinbootmaker KILL || true
-sudo runc delete coinbootmaker || true
-sudo ip link delete cbm-host || true
-sudo ip netns delete coinbootmaker || true
-if mountpoint $MERGED; then
-  sudo umount $MERGED
-fi
-sudo rm -rf $UPPER $LOWER $WORKING_DIRECTORY $MERGED
+while sudo runc list | grep coinbootmaker | grep running; do
+  echo 'Waiting for Coinbootmaker container to be stopped ...'
+  sudo runc kill coinbootmaker KILL
+  sleep 1
+done
+
+while sudo runc list | grep coinbootmaker; do
+  echo 'Waiting for Coinbootmaker container to be cleaned up ...'
+  sudo runc delete coinbootmaker
+  sudo runc kill coinbootmaker KILL || true
+  sudo runc delete coinbootmaker || true
+  sudo ip link delete cbm-host || true
+  sudo ip netns delete coinbootmaker || true
+  if mountpoint $MERGED; then
+    sudo umount $MERGED
+  fi
+  sudo rm -rf $UPPER $LOWER $WORKING_DIRECTORY $MERGED
+  sleep 1
+done
 
 
 sudo mkdir -p $UPPER $LOWER $WORKING_DIRECTORY $MERGED
@@ -80,7 +118,7 @@ cd $LOWER/rootfs
 
 # We have to use 'sudo' for 'cpio' else the ownership of the files in the
 # archive is messed up.
-zcat $INITRAMFS | sudo cpio -idm
+zcat $CACHE_DIR/$INITRAMFS | sudo cpio -idm
 
 # Now we extract the nested initramfs
 # We force to overwrite existing files from busybox with '-u'
